export const MESSAGE = {
  POPUP_GET_STATE: 'POPUP_GET_STATE',
  POPUP_SET_EXTENSION_ENABLED: 'POPUP_SET_EXTENSION_ENABLED',
  POPUP_START_SELECTION: 'POPUP_START_SELECTION',
  POPUP_STOP_SELECTION: 'POPUP_STOP_SELECTION',
  POPUP_RETRY_RULE: 'POPUP_RETRY_RULE',
  POPUP_REMOVE_BLUR_PAGE_ONLY: 'POPUP_REMOVE_BLUR_PAGE_ONLY',
  POPUP_DISABLE_RULE: 'POPUP_DISABLE_RULE',
  POPUP_ENABLE_RULE: 'POPUP_ENABLE_RULE',
  POPUP_DELETE_RULE: 'POPUP_DELETE_RULE',

  CONTENT_BOOTSTRAP: 'CONTENT_BOOTSTRAP',
  CONTENT_SELECTION_CAPTURED: 'CONTENT_SELECTION_CAPTURED',
  CONTENT_RULE_STATUS_UPDATE: 'CONTENT_RULE_STATUS_UPDATE',

  BG_ENTER_SELECTION: 'BG_ENTER_SELECTION',
  BG_EXIT_SELECTION: 'BG_EXIT_SELECTION',
  BG_RETRY_RULE_ON_PAGE: 'BG_RETRY_RULE_ON_PAGE',
  BG_REMOVE_RULE_EFFECT_PAGE: 'BG_REMOVE_RULE_EFFECT_PAGE',
  BG_REMOVE_ALL_EFFECTS_PAGE: 'BG_REMOVE_ALL_EFFECTS_PAGE'
};

export const MATCHER_POLICY = {
  autoApplyThreshold: 0.85,
  ambiguousThreshold: 0.6,
  topGapAmbiguousDelta: 0.05,
  minIndependentCategories: 3,
  minCategoryContribution: 0.65
};

export const RETRY_POLICY = {
  mutationDebounceMs: 150,
  inactivityWindowMs: 5000,
  maxAutoRetryAttemptsPerRulePerLoad: 5
};

export const SETTINGS_KEY = 'pb:settings';
export const SETTINGS_DEFAULT = {
  extensionEnabled: true
};
